name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-format:
    name: Check Python lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 \
          || (echo "flake8(linter)のチェックに失敗しました。上記のエラーを確認して修正し，再度コミット・プッシュしてください。" && exit 1)
      - name: Check import order with isort
        run: |
          isort --check-only --diff --color . \
          || (echo "isort(importのソート順調整)のチェックに失敗しました。上記のファイルを確認して修正し，再度コミット・プッシュしてください。" && exit 1)
      - name: Check formatting with black
        run: |
          black --check --diff --color . \
          || (echo "black(フォーマッタ)のチェックに失敗しました。上記のファイルを確認して修正し，再度コミット・プッシュしてください。" && exit 1)
      - name: Django check
        run: |
          python manage.py check \
          || (echo "Django設定のチェックに失敗しました。上記のエラーを確認して修正し，再度コミット・プッシュしてください。" && exit 1)
      - name: Ensure no migration file is edited
        run: |
          git diff --diff-filter=MD --exit-code ${base_branch} **/migrations/*.py \
          || (echo "一度mainに取り込まれたmigrationファイルを編集してはいけません。元の状態を復元した上で，migration作成を行い直してください。" && exit 1)

  django-test:
    name: Django Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt
      - name: Check migration file is fully generated
        run: |
          python manage.py makemigrations --check \
          || (echo "マイグレーションファイルとコードに差分があります。migrationを生成し，再度コミット・プッシュしてください。" && exit 1)
      - name: Run Django Unit Test
        run: |
          python manage.py test \
          || (echo "Django Unit Testが失敗しました。上記のエラーを確認して修正し，再度コミット・プッシュしてください。" && exit 1)
      - name: Finish
        run: echo "All checks passed!"
